import { useEffect, useState } from "react";

import {
  Container,
  Typography,
  Box
} from "@mui/material";

import Header from "../components/Header";
import FindingsTable from "../components/FindingsTable";
import DashboardSection from "../components/DashboardSection";

import {
  getHistory
} from "../api/securityApi";

function History() {

  const [history,
    setHistory] =
    useState<any[]>([]);

  useEffect(() => {

    const loadData =
      async () => {

        const data =
          await getHistory();

        setHistory(data);

      };

    loadData();

  }, []);

  return (

    <Container
      maxWidth="xl"
      sx={{
        mt: 4,
        mb: 8
      }}
    >

      <Header />

      <Typography
        variant="h4"
        sx={{
          mb: 3,
          fontWeight: 600
        }}
      >
        Historical Findings
      </Typography>

      <Typography
        variant="body1"
        color="text.secondary"
        sx={{ mb: 4 }}
      >
        Complete audit trail of all
        findings generated by scans.
      </Typography>

      <Box>

        <DashboardSection
          title="Historical Findings"
        >

          <FindingsTable
            findings={history}
            showHistoryColumns
          />

        </DashboardSection>

      </Box>

    </Container>

  );
}

export default History;